dist: xenial
language: node_js
node_js: node
cache: yarn
env:
  global:
  - secure: nEoIVbNELnI4Li6RBDZyNn19aax3sS0uk8jokG5oqz01Uo8QnBs6hYzxmVNiGGd2oASlIQ2Y5G9ECdO9H/6svtYYuVjO7uiqXvkNpEvtHZuvsJ4RUZrIzwaOeW1i8LDRYL71ICi2uhMlCcI/bAfcJDWhxU1AMcCLN047TqzVL3/1Kg35S/U9OC0pxro4SATP6wC6J0WPjZB96rGlx+IVB259gSXbOP1JCVyZ/j1vST+n2gineYmH1uJxerbO8u/e34bZTtpe+wTCwJRvfsEk+XQC0sLstE9aQ1dqcDuGgEf6YyiiH/U8HSh3lQntrg/Ckw+HvqJxbgibb7wO4TzQJMvQZGbM20vEVyP05TmtTX/Y9kfHiQpYRD9AGkIFgw/hNwe+b90MM6QOK4VUFFufkyha0V1q/6Hz4Q4w0LTghWTpbW9llV3zzgh3zK2NRFtAfNKbK2I0bAXgLbizPuN0t8XHUbfiQQE3APPJA3Qa58NTrts2hCy00vIUj4G1NSnKiE/3h20aE0O/3jy2HYoOmp4lqqympsiiO58V2FSol9EbCKfG7H/kyCIUsHeisXqXiO5CnoIkq+bwRkxm5T00diTfwWE8pmuWnL34fT4evT/Pygo8r8Qvog9cJm4eez4kxNsU3LKwBY8zoxAMK5xNwep1EVFPak0XGt01Ayp2DgA=
  - secure: HeQRlkMkpHkVgwQzgm2BWu8hpRM1Rao/4jK3gzGEAGjloJdZ5m0FGNOBpIyHoXh10AQAEh+Mw3uqCOBLrxhgG/J47x+2fPu4fEH0+hCDHa+BvWX9noRHp4M/7RqGseH29UzFFerlEhjUkyvXLsq0g2+h6CiZyEEis3sV+nDgU7vI2SNQYwmtwVEn5IfsRTAGH7u58rDbXAFJGbwk2q//H7d8+kR9Atxy3Ho6bu/6brHEDo4B/KjLKhITrQIUGpJh+SHYcku6elw1NOfwO9MUFJLeqFU38+KGDlX91VlRXa+cC7oO/rC7dMK5Rc/+wJ/nRPN4bUe/DogKDYesR50EBDHnKGM2zZWxn7yrQlHkaRHKiJLcf346yvUUOwKLRjBt6+9gaux60U2cwvqAeVU5ItP5ro06DHpKuXdvG3bqyitqp4vSK+2w2xRnEpiY7cK2kPvAuNCrccErP0aiH3RCJuVP+kYkQ8c2F25nIzSTK939Sv5IFX5dCPm/ex5XINh330Oiuium7a17S+YvLQFHTEEl+rk2vTa74rHqUrKuUQjl0OAq1K55Nt5DgF8p7oA8quiaJnbPXoL/zTNhhTkmezcWkndMJ1QT909/tybrZOcN347pmSsfA60ieaRwkQZylAjXvt+2I8dP6lNvX2Wns/B1HRF8HliIJI4B8/Empec=
branches:
  only:
    - master
deploy:
  provider: script
  skip_cleanup: true
  script:
  - yarn release
